In [2]:
import numpy as np
from time import process_time

*Diffierence between numpy and list time*

In [3]:
p = [i for i in range(1,10000000)]
t = process_time()
p = [i+5 for i in p]
e = process_time()
print(e-t)

2.328125


In [4]:
p = np.array([i for i in range(1,10000000)])
t = process_time()
p += 5
e = process_time()
print(e-t)

0.015625


Numpy arrays

In [5]:
l = [1,2,3,4]
print(l)
type(l)

[1, 2, 3, 4]


list

In [6]:
n = np.array([1,2,3,4])
print(n)
type(n)

[1 2 3 4]


numpy.ndarray

1d array

In [7]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


2d array

In [8]:
a.shape

(4,)

In [9]:
# 2d array
b = np.array([(1,2,3,4),(1,2,3,4)])
print(b)
b.shape

[[1 2 3 4]
 [1 2 3 4]]


(2, 4)

In [10]:
c = np.array([1,2,3,3],dtype=float)
print(c)

[1. 2. 3. 3.]


Intial Placeholders

In [11]:
# create a array of Zeroes
a = np.zeros((4,5))
print(a)
# array of ones
a = np.ones((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
# to create a array with a particular value
a = np.full((4,5),45)
print(a)

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]


In [15]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# array with random values
b = np.random.random((3,4))
b

array([[0.71487677, 0.66905846, 0.85656563, 0.45558966],
       [0.84074931, 0.55394328, 0.8457287 , 0.68827669],
       [0.57449492, 0.59959935, 0.78040947, 0.41228199]])

In [18]:
# random integers values array b/w apecific range
a = np.random.randint(10,100,(3,5))
a

array([[20, 39, 61, 73, 25],
       [67, 85, 39, 16, 71],
       [29, 13, 65, 54, 40]])

In [21]:
# array of evenly spaced values --> specifiying no. of values 
d = np.linspace(10,30,7)
d

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        ])

In [23]:
# array of evenly spacesd values --> specifying step
e = np.arange(10,30,5)
e

array([10, 15, 20, 25])

In [25]:
# ont list to array
l = [1,2,3,4]
a = np.asarray(l)
print(a)

[1 2 3 4]


In [26]:
a = np.random.randint(10,90,(5,5))
print(c)

[1. 2. 3. 3.]
