In [3]:
import numpy as np
from time import process_time

*Diffierence between numpy and list time*

In [6]:
p = [i for i in range(1,10000000)]
t = process_time()
p = [i+5 for i in p]
e = process_time()
print(e-t)

1.28125


In [7]:
p = np.array([i for i in range(1,10000000)])
t = process_time()
p += 5
e = process_time()
print(e-t)

0.015625


Numpy arrays

In [8]:
l = [1,2,3,4]
print(l)
type(l)

[1, 2, 3, 4]


list

In [9]:
n = np.array([1,2,3,4])
print(n)
type(n)

[1 2 3 4]


numpy.ndarray

1d array

In [11]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


2d array

In [13]:
a.shape

(4,)

In [15]:
# 2d array
b = np.array([(1,2,3,4),(1,2,3,4)])
print(b)
b.shape

[[1 2 3 4]
 [1 2 3 4]]


(2, 4)

In [16]:
c = np.array([1,2,3,3],dtype=float)
print(c)

[1. 2. 3. 3.]


Intial Placeholders

In [20]:
# create a array of Zeroes
a = np.zeros((4,5))
print(a)
# array of ones
a = np.ones((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
# to create a array with a particular value
a = np.full((4,5),45)
print(a)

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
