In [3]:
import numpy as np
from time import process_time

*Diffierence between numpy and list time*

In [4]:
p = [i for i in range(1,10000000)]
t = process_time()
p = [i+5 for i in p]
e = process_time()
print(e-t)

3.171875


In [5]:
p = np.array([i for i in range(1,10000000)])
t = process_time()
p += 5
e = process_time()
print(e-t)

0.015625


Numpy arrays

In [6]:
l = [1,2,3,4]
print(l)
type(l)

[1, 2, 3, 4]


list

In [7]:
n = np.array([1,2,3,4])
print(n)
type(n)

[1 2 3 4]


numpy.ndarray

1d array

In [8]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


2d array

In [9]:
a.shape

(4,)

In [10]:
# 2d array
b = np.array([(1,2,3,4),(1,2,3,4)])
print(b)
b.shape

[[1 2 3 4]
 [1 2 3 4]]


(2, 4)

In [11]:
c = np.array([1,2,3,3],dtype=float)
print(c)

[1. 2. 3. 3.]


Intial Placeholders

In [12]:
# create a array of Zeroes
a = np.zeros((4,5))
print(a)
# array of ones
a = np.ones((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# to create a array with a particular value
a = np.full((4,5),45)
print(a)

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]


In [14]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# array with random values
b = np.random.random((3,4))
b

array([[0.2022048 , 0.39017522, 0.33121571, 0.69379674],
       [0.87580585, 0.84724008, 0.66241085, 0.16382204],
       [0.04754041, 0.53546308, 0.00241124, 0.46443716]])

In [16]:
# random integers values array b/w apecific range
a = np.random.randint(10,100,(3,5))
a

array([[97, 29, 17, 75, 50],
       [24, 81, 24, 21, 17],
       [75, 23, 56, 28, 85]])

In [17]:
# array of evenly spaced values --> specifiying no. of values 
d = np.linspace(10,30,7)
d

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        ])

In [18]:
# array of evenly spacesd values --> specifying step
e = np.arange(10,30,5)
e

array([10, 15, 20, 25])

In [19]:
# ont list to array
l = [1,2,3,4]
a = np.asarray(l)
print(a)

[1 2 3 4]


In [20]:
a = np.random.randint(10,90,(5,5))
print(a)

[[11 62 86 76 46]
 [62 64 45 83 33]
 [73 22 88 58 35]
 [76 81 51 53 23]
 [64 23 36 68 37]]


In [21]:
print(a.shape)
# no. of dimensons
print(a.ndim)
# no. of elements
print(a.size)
# datatype of vlaues
print(a.dtype)


(5, 5)
2
25
int32


Mathematical Operations

In [22]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,9]
print(l1+l2) # + will concatnate two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 9]


In [26]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[1 2 6]
 [9 2 3]
 [5 4 5]]
[[7 3 9]
 [3 4 6]
 [4 3 1]]
[[ 8  5 15]
 [12  6  9]
 [ 9  7  6]]
[[-6 -1 -3]
 [ 6 -2 -3]
 [ 1  1  4]]
[[ 7  6 54]
 [27  8 18]
 [20 12  5]]
[[0.14285714 0.66666667 0.66666667]
 [3.         0.5        0.5       ]
 [1.25       1.33333333 5.        ]]


In [28]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))



[[ 8  5 15]
 [12  6  9]
 [ 9  7  6]]
[[-6 -1 -3]
 [ 6 -2 -3]
 [ 1  1  4]]
[[ 7  6 54]
 [27  8 18]
 [20 12  5]]
[[0.14285714 0.66666667 0.66666667]
 [3.         0.5        0.5       ]
 [1.25       1.33333333 5.        ]]


Transposing

In [29]:
a = np.random.randint(1,20,(2,3))
print(a)
print(a.shape)

b = np.transpose(a)
print(b)
print(b.shape)


[[14  7 18]
 [ 5  7 14]]
(2, 3)
[[14  5]
 [ 7  7]
 [18 14]]
(3, 2)


In [30]:
a = np.random.randint(1,20,(2,3))
print(a)
print(a.shape)

b = a.T
print(b)
print(b.shape)

[[19  2  4]
 [ 4 12  2]]
(2, 3)
[[19  4]
 [ 2 12]
 [ 4  2]]
(3, 2)


Reshaping

In [31]:
a = np.random.randint(1,20,(2,3))
print(a)
print(a.shape)
b= a.reshape(3,2)
print(b)
print(b.shape)

[[ 7  7 15]
 [ 5 10 19]]
(2, 3)
[[ 7  7]
 [15  5]
 [10 19]]
(3, 2)
